sudo: required

language: go
go:
  - "1.10"

services:
  - docker

script:
  - go run lope.go -noSSH alpine ls
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
